version: "3"
services:
    postgres:
        image: postgres:10.5
        container_name: myproject-postgres
        ports:
            - "15432:5432"
        environment:
            - POSTGRES_PASSWORD=myuserpass
            - POSTGRES_DB=mydb
        volumes:
            - postgres:/var/lib/postgresql/data
        
    pgadmin:
        image: dpage/pgadmin4
        container_name: myproject-pgadmin
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=test@test.com
            - PGADMIN_DEFAULT_PASSWORD=mypass
        volumes:
            - pgadmin:/root/.pgadmin
volumes:
    postgres:
    pgadmin:
